### PR TITLE
net-libs/restbed: ebuild update, new deps added

### LINKED ISSUE #20: net-libs/restbed: ebuild update, new deps added
https://github.com/reagentoo/gentoo-overlay/commit/d77fc1cc6fd156cae55caaf9b2014f38483a83a7

```
RDEPEND="
	>=dev-cpp/asio-1.10
	dev-cpp/kashmir
	sys-libs/zlib
	examples? (
		sys-libs/pam
		virtual/logger
	)
	ssl? ( dev-libs/openssl )
	test? ( dev-cpp/catch )
"
```
May be you want to merge this commit?

### PR DESCRIPTION
**Pull request by YogSottot**
fix #20

### CODE REVIEW

**Comment by stefan-langenmaier** [comment]
Why is there a need for an asio live ebuild or maybe in restbed-9999 the dependency to asio should also be to the live version. To me it looks like there is no release 1.11 version, yet.

Is there a build problem with 1.10.8?

**Comment by YogSottot** [comment]
Yes, there is
```
In file included from /var/tmp/portage/net-libs/restbed-9999/work/restbed-9999/source/corvusoft/restbed/http.cpp:22:0:
/var/tmp/portage/net-libs/restbed-9999/work/restbed-9999/source/corvusoft/restbed/detail/socket_impl.hpp:24:38: fatal error: asio/io_service_strand.hpp: No such file or directory
 #include <asio/io_service_strand.hpp>
                                      ^
compilation terminated.
make[2]: *** [CMakeFiles/restbed.dir/build.make:111: CMakeFiles/restbed.dir/source/corvusoft/restbed/http.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/var/tmp/portage/net-libs/restbed-9999/work/restbed-9999_build'
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/restbed.dir/all] Error 2
make[1]: Leaving directory '/var/tmp/portage/net-libs/restbed-9999/work/restbed-9999_build'
make: *** [Makefile:128: all] Error 2
 * ERROR: net-libs/restbed-9999::neko-local failed (compile phase):
 *   emake failed
```

**Comment by YogSottot** [comment]
And yes, there is no 1.11 release, so it automatically depend over asio-9999
I changed dep, if it preferred.

**Comment by stefan-langenmaier** [comment]
Thanks, for changing the dep!

**Pull request merged**
