### PR TITLE
[Close stefan-langenmaier/ring-overlay#11] Added patches from the ring project

### PR DESCRIPTION
**Pull request by YogSottot**
Added patches from the ring project

More about patches https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=843654#20

### CODE REVIEW

**Comment by YogSottot** [comment]
> RepoMan scours the neighborhood...
  file.size.fatal [fatal]       1
  (113 KiB) net-libs/pjproject/files/gnutls.patch

This patch can be split if it necessary

**Comment by stefan-langenmaier** [comment]
Thanks for your work! I don't think it's necessary to split the patch. I would be better if we could stick with the same files that are also use by the Ring team. That should reduce the confusion in the future.

No problem if repoman fails. :)

**Comment by stefan-langenmaier** [comment]
I'll try to merge it this afternoon.

**Comment by YogSottot** [comment]
Files slightly altered because of the "offset lines" and "fuzzy" and "unexpected end of file warnings".
@@ -l,s +l,s @@
Just change the «l» part. And added more context when it need.

**Comment by stefan-langenmaier** [comment]
The pull request is merged. Thanks again.

I tried to specify in the ring-daemon ebuild the dependency on pjproject to only consider this repository.
It seem that the following code works only on the command line but not in the DEPEND list: `net-voip/pjproject::ring-overlay`.

So I tried to work around it with a very specific slot. Maybe you have a better idea.

**Comment by YogSottot** [comment]
[Repository Dependency](https://dev.gentoo.org/~zmedico/portage/doc/ch06s03s06.html#package-ebuild-eapi-4-python-metadata-repository-dependencies) is removed long time ago.

https://bugs.gentoo.org/show_bug.cgi?id=427076

I suppose it can be added in eclass in this repo. But i think, that slot is ok.

**Comment by stefan-langenmaier** [comment]
Good to know. :)

**Pull request merged**
